//auth action types
export const START_AUTH = 'START_AUTH'
export const SUCCESS_AUTH = 'SUCCESS'
export const SUCCESS_UPLOAD = 'SUCCESS_UPLOAD'
export const FAIL_AUTH = 'FAIL_AUTH'
export const LOGOUT_AUTH = 'LOGOUT_AUTH'
export const SET_LOGGED_USER = 'SET_LOGGED_USER'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const GET_PROFILE = 'GET_PROFILE'
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND'
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE'
export const GET_PROFILES = 'GET_PROFILES'
